// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          int64              `json:"id"`
	FirstName   string             `json:"first_name"`
	MiddleName  pgtype.Text        `json:"middle_name"`
	LastName    string             `json:"last_name"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	Pesel       string             `json:"pesel"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserAddress struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	Postcode        string             `json:"postcode"`
	Street          string             `json:"street"`
	BuildingNumber  string             `json:"building_number"`
	ApartmentNumber pgtype.Text        `json:"apartment_number"`
	City            string             `json:"city"`
	Country         string             `json:"country"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type UserConsent struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	ConsentType string             `json:"consent_type"`
	Version     string             `json:"version"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	IpAddress   *netip.Addr        `json:"ip_address"`
}
