// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInitialRegistration = `-- name: CreateInitialRegistration :one

INSERT INTO users (
    pesel,
    first_name,
    middle_name,
    last_name,
    date_of_birth
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, pesel, first_name, middle_name, last_name, date_of_birth, created_at, updated_at
`

type CreateInitialRegistrationParams struct {
	Pesel       string      `json:"pesel"`
	FirstName   string      `json:"first_name"`
	MiddleName  pgtype.Text `json:"middle_name"`
	LastName    string      `json:"last_name"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
}

type CreateInitialRegistrationRow struct {
	ID          int64              `json:"id"`
	Pesel       string             `json:"pesel"`
	FirstName   string             `json:"first_name"`
	MiddleName  pgtype.Text        `json:"middle_name"`
	LastName    string             `json:"last_name"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// queries.sql
func (q *Queries) CreateInitialRegistration(ctx context.Context, arg CreateInitialRegistrationParams) (CreateInitialRegistrationRow, error) {
	row := q.db.QueryRow(ctx, createInitialRegistration,
		arg.Pesel,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.DateOfBirth,
	)
	var i CreateInitialRegistrationRow
	err := row.Scan(
		&i.ID,
		&i.Pesel,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPesel = `-- name: GetUserByPesel :one
SELECT id, pesel, first_name, middle_name, last_name, date_of_birth, created_at, updated_at
FROM users
WHERE pesel = $1
`

type GetUserByPeselRow struct {
	ID          int64              `json:"id"`
	Pesel       string             `json:"pesel"`
	FirstName   string             `json:"first_name"`
	MiddleName  pgtype.Text        `json:"middle_name"`
	LastName    string             `json:"last_name"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByPesel(ctx context.Context, pesel string) (GetUserByPeselRow, error) {
	row := q.db.QueryRow(ctx, getUserByPesel, pesel)
	var i GetUserByPeselRow
	err := row.Scan(
		&i.ID,
		&i.Pesel,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
