// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// queries.sql
	CreateInitialRegistration(ctx context.Context, arg CreateInitialRegistrationParams) (CreateInitialRegistrationRow, error)
	GetUserByPesel(ctx context.Context, pesel string) (GetUserByPeselRow, error)
}

var _ Querier = (*Queries)(nil)
